### ISSUE TITLE
Apply perturbations to data

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators2#11]
After we know the adversarial techniques to use, apply to all corpus.
Need to think on how to do this without under or overdoing it.
For example, if we are changing tense, should this be applied to all applicable words or 50% of each data unit, etc.?

**Comment by edponce** [comment]
Based on Edmon's initial comments on perturbation ideas, synonyms and change of active/passive voice seem acceptable.

For synonyms you might need to identify parts-of-speech first to identify nouns, adjectives. Gensim and spaCy have POS capabilities. For list of words, you might consider GNU Aspell list of words. The difficult part is mapping words that are synonyms.

**Comment by edponce** [comment]
We still do not have a *perturbation percent*, that is, how much change is acceptable. It seems that this will be identified via a combination of testing and Edmon's instructions.

**Comment by edponce** [comment]
The 2 perturbations we will apply to the data are: synonyms (@groppcw) and US/British English translation (@MikeynJerry).

The question on how much perturbation to apply to each document will depend on the perturbation itself. Some approaches will modify more text than others.

We suggest to limit the perturbation effect to 20% for each document. If a perturbation changes less than 20%, then you can consider all its changes. If a perturbation exceeds the 20%, then limit it.

**Comment by MikeynJerry** [comment]
US/British English translation code has been added in 8554796

**Comment by edponce** [comment]
@quanqhow made a synonyms replacement code using WordNet synonyms.

**Comment by edponce** [comment]
Given that the code for both approaches takes text as input, we will control the perturbation limit by limiting and randomizing the input given to these codes.
