### ISSUE TITLE
Create training, testing, and validation dataset

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators2#5]
Data unit: 1/2, 2, 5 pages
Validation dataset: 20% from author’s corpus, 80% from other authors

**Comment by groppcw** [comment]
@edponce Is my responsibility here more about locating data or about carving up data we already have?

**Comment by edponce** [comment]
Honestly, it is simply to for you to help the group identify how these data should be created. Given that you have been assigned to other "complex" tasks, you do not need to implement this. I will reassign this task later on.
